Reselling/UIView/Controllers/MainController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Reselling.Domain.Infrastructure;
using Reselling.Domain.Models.Data;
using Reselling.UIView.Models.Data;
using System;
using System.Linq;
using System.Threading;

namespace Resaling.Controllers
{
    public class MainController : Controller
    {

        IRepository _repo;
        readonly int _eventsPageSize = 4;
        readonly int _ticketsForEventsPageSize = 4;


        public MainController(IRepository repo)
        {
            _repo = repo;
        }

        // GET: /<controller>/
        public IActionResult Events(int? page)
        {
            int _page = (int)(page ?? 1);

            EventsListViewModel _eventsList = new EventsListViewModel
            {
                EventsItems = _repo.GetEvents().Skip((_page - 1) * _eventsPageSize).Take(_eventsPageSize),
                PagingInfo = new PagingInfo
                {
                    CurentPage = _page,
                    ItemsRerPage = _eventsPageSize,
                    TotalItems = _repo.GetEvents().Count()
                }
            };


            return View(_eventsList);
        }

        public IActionResult TicketsEvent(int? id, int? page)
        {
            EventTicketsListView _eventsList;

            if (id != null)
            {
                int _id = (int)id;

                Event _event = _repo.GetEventById(_id);

                if (_event != null)
                {
                    int _page = (int)(page ?? 1);
                    _eventsList = new EventTicketsListView
                    {
                        Event = _event,


                        PagingInfo = new PagingInfo
                        {
                            CurentPage = _page,
                            ItemsRerPage = _ticketsForEventsPageSize,
                            TotalItems = _event.Tickets.Count()
                        }
                    };
                    return View(_eventsList);
                }
            }
            return RedirectToAction("Events");
        }


        public IActionResult SetLanguage(string culture, string returnUrl)
        {

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

                     
             return LocalRedirect(returnUrl);

            // return View(System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName);culture
        }
    }
}

Reselling/UIView/Views/Main/Events.cshtml
@model EventsListViewModel

<h1>Events</h1>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                @foreach (var e in Model.EventsItems)
                {

                    <div class="section">
                        <div class="container">
                            <hr>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="@Url.Action("TicketsEvent", new {id = e.Id, page = 1 })">
                                        <img src="~/images/@e.Banner"
                                             class="img-responsive">
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    <h2>@e.Name</h2>
                                    <h3>@e.Venue.City.Name</h3>
                                    <h4>@e.Venue.Name</h4>
                                    <h4>@e.Date.ToString("f")</h4>
                                    <p>
                                        <br>
                                        <br>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                             
            </div>
        </div>
    </div>
</div>
@Html.PageLinks(Model.PagingInfo, x => Url.Action("Events", new { page = x }))

Reselling/UIView/Views/Main/TicketsEvent.cshtml
@model EventTicketsListView

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <img src="~/images/@Model.Event.Banner"
                                     class="img-responsive">
                            </div>
                            <div class="col-md-6">
                                <h2>@Model.Event.Name</h2>
                                <h3>@Model.Event.Venue.City.Name</h3>
                                <h4>@Model.Event.Venue.Name</h4>
                                <h4>@Model.Event.Date.ToString("f")</h4>
                                <h4>@Model.Event.Description</h4>
                                <p>
                                    <br>
                                    <br>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container">
        <hr>
        <div class="row">
            <p>
                <br>
            </p>
            <div class="col-md-12">
                @if (Model.PagingInfo.TotalItems > 0)
                {
                    int i = 1;
                    <table class="table">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>@Localizer["SellerName"]</th>
                                <th>@Localizer["Price"]</th>
                                <th>@Localizer["SellerNotes"]</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Ticket t in Model.Event.Tickets)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@t.User.FirstName  @t.User.LastName</td>
                                    <td>@t.Price</td>
                                    <td>@t.Note</td>
                                    <td>
                                        <div class="col-md-1">
                                            <a asp-action="Order" asp-controller="Main" asp-route-id="@t.Id"
                                               class = "btn btn-primary">@Localizer["Grab"]
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                i++;

                            }

                        </tbody>
                    </table>
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("TicketsEvent", new { id = @Model.Event.Id, page = x }))

                }
                else
                {
                    <h2>@Localizer["NoTickets"]</h2>
                }
            </div>
        </div>
    </div>
</div>